### ISSUE TITLE
Does this plugin remove unassociated tags?

### ISSUE THREAD

**Issue by bozdoz** [alex/django-taggit#227] opened 2014-04-16 20:19 UTC
I'm wondering if this can replace our model in our project.  We have a tagging system with a manytomany field, but when the tags are removed from the tagged object, there's no reliable way to clean up the discarded tags, other than to run a cron job.  Does this plugin have that functionality?

**Comment by charlex** [comment] 2016-09-07 06:50
#294 is related

**Comment by jdufresne** [comment] 2018-08-06 15:31
Thanks for reporting. This issue looks like a duplicate of #111. If you have additional information to add, please do so there.

**Closed by jdufresne** 2018-08-06 15:31 UTC
