### ISSUE TITLE
Duplicate entry 'TEST' for key 'name'

### ISSUE THREAD

**Issue by KarDer** [alex/django-taggit#320] opened 2015-06-23 19:13 UTC
If you enter a tag "test"
Then enter the "TEST"

You will see an error: __Duplicate entry 'TEST' for key name__
It would be good not to pay attention to the upper case

**Comment by seocam** [comment] 2016-02-03 13:14
This is a duplicate of #308

**Closed** 2016-02-03 14:01 UTC
