### ISSUE TITLE
related.py gone in 1.8

### ISSUE THREAD

**Issue by phoebebright** [alex/django-taggit#284] opened 2014-12-30 14:28 UTC
See this ticket: https://code.djangoproject.com/ticket/21414

Currently failing when running dev version of 1.8 with error:

No module named related

**Comment by collinanderson** [comment] 2015-01-02 01:14
Looks like Tim Graham confirmed your idea, but I ran into more and more problems even after that.

**Comment by collinanderson** [comment] 2015-01-02 01:21
I should mention that things are going to change again after https://github.com/django/django/pull/3114 is merged.

**Comment by collinanderson** [comment] 2015-01-08 13:43
Ok, the meta refactor has been merged. We could probably start working on getting compatible with 1.8 again.

**Comment by phoebebright** [comment] 2015-02-09 11:00
Now getting this error with 1.8a1

      File "/Users/phoebebr/.virtualenvs/gmd3/lib/python2.7/site-packages/taggit/managers.py", line 311, in post_through_setup
        self.related = ForeignObjectRel(cls, self.model, self)
    AttributeError: can't set attribute

with simplest model:

    class Question(models.Model):
        title    = models.CharField(max_length=200)
        tags = TaggableManager()

But ok with 1.7

**Comment by RossLote** [comment] 2015-03-05 09:39
I found this in django 1.8

    class RelatedField(Field):
        ...
        @property
        def related(self):
            warnings.warn(
                "Usage of field.related has been deprecated. Use field.rel instead.",
                RemovedInDjango20Warning, 2)
            return self.rel

So I'd think that this would fix it:
change this:

    self.related = RelatedObject(self.through, cls, self)

for this:

    self.rel = ForeignObjectRel(cls, self.model, self)

but then the TaggableManager rel attribute will have to be renamed

Any thoughts?

**Comment by RossLote** [comment] 2015-03-05 10:12
This is quite frustrating as this is one of two apps that will now be broke in my site and they aren't straight forward fixes. This:

> Private attribute django.db.models.Field.related is deprecated in favor of Field.rel. The latter is an 
> instance of django.db.models.fields.related.ForeignObjectRel which replaces 
> django.db.models.related.RelatedObject

to me implies that it's a drop in replacement but it just doesn't seem to work that way.

**Comment by kaedroho** [comment] 2015-03-15 17:18
I've got all the tests working on Django 1.8 beta 2 in my pull request (#297). Is it possible that you could try this on your sites and let me know if you hit any issues?

@RossLote 
I solved the related/rel issue by removing the ``self.related = RelatedObject()`` (https://github.com/kaedroho/django-taggit/commit/255a0ca3698374fcd6a7df0bbcda55e6241edf59) and passing the ``TaggableRel`` object as an argument into the field constructor (https://github.com/kaedroho/django-taggit/commit/986d9e9a771623cecc27f4ba3941d99fb43fca67). ``TaggableRel`` is a subclass of ``ForeignObjectRel``.

**Comment by collinanderson** [comment] 2015-03-16 21:56
#297 works for me on my site. Thanks so much!

**Comment by JoeReis** [comment] 2015-04-02 14:08
Any idea when this issue will be fixed for Django 1.8 (released today)? Getting RelatedObject errors, such as ```ImportError: No module named 'django.db.models.related```

**Comment by frewsxcv** [comment] 2015-04-03 06:21
This should be fixed now

https://github.com/alex/django-taggit/pull/297#issuecomment-89159013

**Closed by frewsxcv** 2015-04-03 06:21 UTC

**Comment by hassanahmadi2012** [comment] 2016-10-04 12:09
ok
