### ISSUE TITLE
Duplicate entry error during "add"

### ISSUE THREAD

**Issue by gluwa** [alex/django-taggit#375] opened 2016-01-21 10:12 UTC
I was getting

    IntegrityError: (1062, "Duplicate entry 'foobar' for key 'name'")

a lot and investigated the issue.
While `_TaggableManager.add()` is running, some existing tags ended up in `tags_to_create` and caused the error above.

I'm not sure why this is happening yet but it might have to do with the fact that I have changed `TAGGIT_CASE_INSENSITIVE ` from `False` to `True`, and my `slugify` method.

I had to change 

    for new_tag in tags_to_create:
        tag_objs.add(self.through.tag_model().objects.create(name=new_tag))

into

    for new_tag in tags_to_create:
        new_tag_obj, created = self.through.tag_model().objects.get_or_create(name=new_tag)
        tag_objs.add(new_tag_obj)

to avoid this problem.
Did any of you encountered the same problem before? I will update when I find the exact cause and solution.

**Comment by seocam** [comment] 2016-02-03 13:15
Looks like a duplicate of #308.

**Closed** 2016-02-03 14:01 UTC
