### ISSUE TITLE
How can I delete unused tags ?

### ISSUE THREAD

**Issue by ghost** [alex/django-taggit#294] opened 2015-03-08 15:37 UTC
I'm trying to delete unused tags in django, but I don't know how to do it, how can I do it?

**Comment by kurtw** [comment] 2016-02-08 20:07
You could go into the database directly and delete them, or you could write a script that looks for tags in the taggit_tag table that aren't assigned. There are other ways too. I'm currently running into this.

**Comment by PaulMest** [comment] 2016-12-16 00:15
Here is a simple way to delete tags which are not associated with anything:
```
from taggit.models import Tag

def remove_all_tags_without_objects():
    for tag in Tag.objects.all():
        if tag.taggit_taggeditem_items.count() == 0:
            print('Removing: {}'.format(tag))
            tag.delete()
        else:
            print('Keeping: {}'.format(tag))
```

**Comment by jdufresne** [comment] 2018-08-06 15:29
Thanks for reporting. This issue looks like a duplicate of #111. If you have additional information to add, please do so there.

**Closed by jdufresne** 2018-08-06 15:29 UTC

**Comment by saileshkush95** [comment] 2018-09-24 02:26
> Here is a simple way to delete tags which are not associated with anything:
> 
> ```
> from taggit.models import Tag
> 
> def remove_all_tags_without_objects():
>     for tag in Tag.objects.all():
>         if tag.taggit_taggeditem_items.count() == 0:
>             print('Removing: {}'.format(tag))
>             tag.delete()
>         else:
>             print('Keeping: {}'.format(tag))
> ```

How to use this and where to use this?

**Comment by PaulMest** [comment] 2018-09-24 05:12
@saileshkush95 
You could put it inside a [Custom Management Command](https://docs.djangoproject.com/en/2.1/howto/custom-management-commands/).

**Comment by kurtrwall** [comment] 2018-09-27 15:54
> You could put it inside a Custom Management Command.

you might be able to hook into your database event system to trigger it as well
